# Generated by Django 5.2.10 on 2026-02-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_description_alter_task_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('active', 'Активный'), ('completed', 'Завершенный'), ('on_hold', 'На паузе')], default='active', max_length=20, verbose_name='Статус'),
        ),
    ]
